Adding Error log creation to Samuel-workflow
Adding error log creation on request. Only append when error occurs. Still creates an error log if no errors are created (Testing of function).

diff --git a/.github/workflows/Samuel-workflow.yml b/.github/workflows/Samuel-workflow.yml
--- a/.github/workflows/Samuel-workflow.yml
+++ b/.github/workflows/Samuel-workflow.yml
@@ -5,6 +5,12 @@ name: Samuel Workflow
 
 on:
   workflow_dispatch:
+    inputs:
+      ErrorLog:
+        description: "Should a Error log be generated?"
+        required: true
+        default: 'false'
+        type: boolean
 
 permissions:
   contents: read
@@ -20,21 +26,30 @@ jobs:
       uses: actions/setup-python@v3
       with:
         python-version: "3.10"
+        
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+        
     - name: Lint with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+        
     - name: Test with pytest
       run: |
-        pytest
-  
+        pytest || true
+        
+    - name: Create Errorlog
+      if: failure || github.events.inputs.ErrorLog == 'true'
+      run: |
+        echo "Error log generated because of step error or user request." > error.log
+        pytest >> error.log || true
+
   docker:
     runs-on: ubuntu-latest
     needs: pytest
@@ -50,16 +65,24 @@ jobs:
           password: ${{ secrets.DOCKER_SAMUEL_PASSWORD }}
 
       - name: Build Docker image
-        run: docker build -t devops .
+        run: docker build -t devops . || echo "Docker build failed" >> error.log
 
       - name: Tag Docker image with latest
-        run: docker tag devops ${{ secrets.DOCKER_SAMUEL_USERNAME }}/devops:latest
+        run: docker tag devops ${{ secrets.DOCKER_SAMUEL_USERNAME }}/devops:latest || echo "Docker tag latest failed" >> error.log
 
-      - name: Tag Docker image with '1.1'
-        run: docker tag devops ${{ secrets.DOCKER_SAMUEL_USERNAME }}/devops:1.2
-
-
-      # Step 5: Push the Docker image to Docker Hub
       - name: Push Docker image to Docker Hub
-        run: docker push ${{ secrets.DOCKER_SAMUEL_USERNAME }}/devops:latest
+        run: docker push ${{ secrets.DOCKER_SAMUEL_USERNAME }}/devops:latest || echo "Docker push failed" >> error.log
+
+  upload-Error-Log:
+    name: Upload Error log
+    runs-on: ubuntu-latest
+    steps:
+    - name: Upload error.log
+      if: always() && (failure || github.events.inputs.ErrorLog == 'true')
+      uses: actions/upload-artifact@v3
+      with:
+        name: error-log
+        path: error.log
+    
+    
 
